minor bug fixes
lerch-a/HaplotypR pull request #10
Opened 2019-10-29 07:53 UTC by jemunro

2019-10-29 15:23 UTC, lerch-a commented on R/processReads.R
> +    outputFile <- file.path(outputDir, sub("_R1.fastq.gz$", "", basename(fastqFileR1[i])))
Hm, the output file should not have _R1 nor _F postfix.

2019-10-29 15:25 UTC, lerch-a commented on R/callHaplotype.R
> +        if(length(hIdx)>2) {
I don't like the space here. Can you make sure not to introduce such whitespace character.

2019-10-29 22:30 UTC, lerch-a commented on R/processReads.R
> +    outputFile <- file.path(outputDir, sub("_R1.fastq.gz$", "", basename(fastqFileR1[i])))
I checked that and the old version with 'sub("_F\\.fastaq.gz" ...' is correct. Why do you think this is a bug?

2019-10-29 22:33 UTC, lerch-a commented on R/callHaplotype.R
> +      tab <- callHaplotype(haplotypesSample[,i, drop=F], minHaplotypCoverage=minHaplotypCoverage,
good catch! I was really tired on Sunday.

2019-10-29 22:40 UTC, lerch-a requested changes
In processReads.R the changes from 
outputFile <- file.path(outputDir, sub("_F\\.fastq.gz", "", basename(fastqFileR1[i])))
to 
outputFile <- file.path(outputDir, sub("_R1\\.fastq.gz$", "", basename(fastqFileR1[i])))
are wrong. The files have a "_F" postfix after removePrimer! Reverse the this change and then I accept the pull request.

2019-10-30 00:37 UTC, jemunro commented on R/processReads.R
> +    outputFile <- file.path(outputDir, sub("_R1.fastq.gz$", "", basename(fastqFileR1[i])))
My mistake - I am working on some code for running HaplotypR in parallel by splitting fastq files, and I had a different extension on some of them.
For greater flexibility and consistency with demultiplexByMarker I have added the trimFilenameExt argument with default value "_F\\.fastq.gz$"

2019-10-30 00:40 UTC, jemunro commented
changes implemented.

2019-10-30 21:15 UTC, merged

2019-10-30 21:16 UTC, lerch-a commented
Thanks.